package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.Detailed;
import com.elextec.persist.model.mybatis.DetailedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DetailedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    int countByExample(DetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    int deleteByExample(DetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    int insert(Detailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    int insertSelective(Detailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    List<Detailed> selectByExample(DetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    Detailed selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Detailed record, @Param("example") DetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Detailed record, @Param("example") DetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Detailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Detailed record);
}