package com.elextec.persist.dao.mybatis;

import com.elextec.persist.model.mybatis.PaymentPlugin;
import com.elextec.persist.model.mybatis.PaymentPluginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentPluginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    int countByExample(PaymentPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    int deleteByExample(PaymentPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    int insert(PaymentPlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    int insertSelective(PaymentPlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    List<PaymentPlugin> selectByExample(PaymentPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    PaymentPlugin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PaymentPlugin record, @Param("example") PaymentPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PaymentPlugin record, @Param("example") PaymentPluginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentPlugin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentPlugin record);
}