package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.PaymentType;
import java.io.Serializable;
import java.util.Date;

public class Detailed implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detailed
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -5459288905888260211L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.mch_id
     *
     * @mbggenerated
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.type
     *
     * @mbggenerated
     */
    private PaymentType type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.order_time
     *
     * @mbggenerated
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.payment_time
     *
     * @mbggenerated
     */
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.id
     *
     * @return the value of detailed.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.id
     *
     * @param id the value for detailed.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.mch_id
     *
     * @return the value of detailed.mch_id
     *
     * @mbggenerated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.mch_id
     *
     * @param mchId the value for detailed.mch_id
     *
     * @mbggenerated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.type
     *
     * @return the value of detailed.type
     *
     * @mbggenerated
     */
    public PaymentType getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.type
     *
     * @param type the value for detailed.type
     *
     * @mbggenerated
     */
    public void setType(PaymentType type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.state
     *
     * @return the value of detailed.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.state
     *
     * @param state the value for detailed.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.order_time
     *
     * @return the value of detailed.order_time
     *
     * @mbggenerated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.order_time
     *
     * @param orderTime the value for detailed.order_time
     *
     * @mbggenerated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.payment_time
     *
     * @return the value of detailed.payment_time
     *
     * @mbggenerated
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.payment_time
     *
     * @param paymentTime the value for detailed.payment_time
     *
     * @mbggenerated
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed.result
     *
     * @return the value of detailed.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed.result
     *
     * @param result the value for detailed.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }
}