package com.elextec.persist.model.mybatis;

import java.io.Serializable;
import java.util.Date;

public class Payment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = -8506893729389242487L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.alipay_private_key
     *
     * @mbggenerated
     */
    private String alipayPrivateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.mch_id
     *
     * @mbggenerated
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.wechat_private_key
     *
     * @mbggenerated
     */
    private String wechatPrivateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.id
     *
     * @return the value of payment.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.id
     *
     * @param id the value for payment.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.name
     *
     * @return the value of payment.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.name
     *
     * @param name the value for payment.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.icon
     *
     * @return the value of payment.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.icon
     *
     * @param icon the value for payment.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.app_id
     *
     * @return the value of payment.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.app_id
     *
     * @param appId the value for payment.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.alipay_private_key
     *
     * @return the value of payment.alipay_private_key
     *
     * @mbggenerated
     */
    public String getAlipayPrivateKey() {
        return alipayPrivateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.alipay_private_key
     *
     * @param alipayPrivateKey the value for payment.alipay_private_key
     *
     * @mbggenerated
     */
    public void setAlipayPrivateKey(String alipayPrivateKey) {
        this.alipayPrivateKey = alipayPrivateKey == null ? null : alipayPrivateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.mch_id
     *
     * @return the value of payment.mch_id
     *
     * @mbggenerated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.mch_id
     *
     * @param mchId the value for payment.mch_id
     *
     * @mbggenerated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.wechat_private_key
     *
     * @return the value of payment.wechat_private_key
     *
     * @mbggenerated
     */
    public String getWechatPrivateKey() {
        return wechatPrivateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.wechat_private_key
     *
     * @param wechatPrivateKey the value for payment.wechat_private_key
     *
     * @mbggenerated
     */
    public void setWechatPrivateKey(String wechatPrivateKey) {
        this.wechatPrivateKey = wechatPrivateKey == null ? null : wechatPrivateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.create_time
     *
     * @return the value of payment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.create_time
     *
     * @param createTime the value for payment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.update_time
     *
     * @return the value of payment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.update_time
     *
     * @param updateTime the value for payment.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}