package com.elextec.persist.model.mybatis;

import com.elextec.persist.field.enums.PaymentType;
import java.io.Serializable;
import java.util.Date;

public class PaymentPlugin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_plugin
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1339906973505054748L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_plugin.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_plugin.mch_id
     *
     * @mbggenerated
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_plugin.payment_type
     *
     * @mbggenerated
     */
    private PaymentType paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_plugin.config
     *
     * @mbggenerated
     */
    private String config;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_plugin.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_plugin.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_plugin.id
     *
     * @return the value of payment_plugin.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_plugin.id
     *
     * @param id the value for payment_plugin.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_plugin.mch_id
     *
     * @return the value of payment_plugin.mch_id
     *
     * @mbggenerated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_plugin.mch_id
     *
     * @param mchId the value for payment_plugin.mch_id
     *
     * @mbggenerated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_plugin.payment_type
     *
     * @return the value of payment_plugin.payment_type
     *
     * @mbggenerated
     */
    public PaymentType getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_plugin.payment_type
     *
     * @param paymentType the value for payment_plugin.payment_type
     *
     * @mbggenerated
     */
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_plugin.config
     *
     * @return the value of payment_plugin.config
     *
     * @mbggenerated
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_plugin.config
     *
     * @param config the value for payment_plugin.config
     *
     * @mbggenerated
     */
    public void setConfig(String config) {
        this.config = config == null ? null : config.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_plugin.create_time
     *
     * @return the value of payment_plugin.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_plugin.create_time
     *
     * @param createTime the value for payment_plugin.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_plugin.update_time
     *
     * @return the value of payment_plugin.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_plugin.update_time
     *
     * @param updateTime the value for payment_plugin.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}