spring:
  profiles:
    active: dev
  mvc:
    media-types.*: text/html;application/json
  devtools:
    restart:
      additional-paths: src/main/java
      exclude: src/main/resources/static/**,src/main/resources/templates/**
  http:
    multipart:
      #默认支持文件上传
      enabled: true
      #单个文件最大限制
      max-file-size: 10Mb
      #总文件最大限制
      max-request-size: 30Mb
logging:
  config: classpath:logback.xml
localsetting:
  platform-type: all
  login-overtime-sec: 3600
  login-overtime-sec-mobile: 3600
  default-password:  123456
  nofilters:
  white-flag: false
  white-url:
  black-flag: true
  black-url:
  cors:
    flag: true
  sms:
    url: http://112.74.76.186:8030/service/httpService/httpInterface.do
    username: JSM41961
    password: 5tjfzvne
    verycode: upxg5dedtrk2
    tempid1: JSM41961-0001
  track-stay-time: 900000
  move-speed-threshold: 16